'use client';
import { useEffect, useState } from 'react';

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:8000';

interface GeneratedDoc {
  id: string;
  user_email: string;
  template_name: string;
  domain_name: string;
  validation_status: string;
  output_language: string;
  created_at: string;
}

function getAuthHeader(): Record<string, string> {
  const token = typeof window !== 'undefined'
    ? (localStorage.getItem('admin_token') || localStorage.getItem('auth_token'))
    : null;
  return token ? { Authorization: `Bearer ${token}` } : {};
}

const STATUS_CLASSES: Record<string, string> = {
  valid:   'bg-green-50 text-green-700',
  pending: 'bg-yellow-50 text-yellow-700',
  invalid: 'bg-red-50 text-red-700',
};

export default function GeneratedDocumentsPage() {
  const [docs, setDocs] = useState<GeneratedDoc[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [exporting, setExporting] = useState<{ id: string; fmt: string } | null>(null);

  useEffect(() => { load(); }, []);

  const load = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch(`${API_BASE}/api/generate`, { headers: getAuthHeader() });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.detail ?? 'Failed to load');
      setDocs(Array.isArray(data) ? data : []);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const doExport = async (docId: string, fmt: 'pdf' | 'docx') => {
    setExporting({ id: docId, fmt });
    try {
      const res = await fetch(`${API_BASE}/api/generate/${docId}/export?format=${fmt}`, {
        headers: getAuthHeader(),
      });
      if (!res.ok) throw new Error(`Export failed: ${res.status}`);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `document-${docId.slice(0, 8)}.${fmt}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e: any) {
      alert(`Export failed: ${e.message}`);
    } finally {
      setExporting(null);
    }
  };

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-900 mb-2">Generated Documents</h1>
      <p className="text-gray-500 text-sm mb-6">
        All documents generated by users via the AI chat assistant
      </p>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 rounded-lg p-3 text-sm mb-4">
          {error}
        </div>
      )}

      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading…</div>
      ) : (
        <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-100">
              <tr>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">Template</th>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">Domain</th>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">User</th>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">Language</th>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">Status</th>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">Created</th>
                <th className="text-left px-4 py-3 font-semibold text-gray-600">Download</th>
              </tr>
            </thead>
            <tbody>
              {docs.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center py-8 text-gray-400">
                    No generated documents yet
                  </td>
                </tr>
              ) : (
                docs.map((doc) => (
                  <tr key={doc.id} className="border-b border-gray-50 hover:bg-gray-50 transition">
                    <td className="px-4 py-3 font-medium text-gray-900">{doc.template_name}</td>
                    <td className="px-4 py-3 text-gray-600">{doc.domain_name}</td>
                    <td className="px-4 py-3 text-gray-500 text-xs">{doc.user_email}</td>
                    <td className="px-4 py-3 text-gray-500 capitalize">{doc.output_language}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_CLASSES[doc.validation_status] ?? 'bg-gray-100 text-gray-600'}`}>
                        {doc.validation_status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-500 text-xs">
                      {new Date(doc.created_at).toLocaleString()}
                    </td>
                    <td className="px-4 py-3">
                      {doc.validation_status === 'valid' ? (
                        <div className="flex gap-2">
                          <button
                            onClick={() => doExport(doc.id, 'pdf')}
                            disabled={exporting?.id === doc.id}
                            className="text-red-600 hover:text-red-800 text-xs font-medium disabled:opacity-50"
                          >
                            {exporting?.id === doc.id && exporting.fmt === 'pdf' ? '…' : 'PDF'}
                          </button>
                          <button
                            onClick={() => doExport(doc.id, 'docx')}
                            disabled={exporting?.id === doc.id}
                            className="text-blue-600 hover:text-blue-800 text-xs font-medium disabled:opacity-50"
                          >
                            {exporting?.id === doc.id && exporting.fmt === 'docx' ? '…' : 'DOCX'}
                          </button>
                        </div>
                      ) : (
                        <span className="text-xs text-gray-400">—</span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
